{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storj-multinode.serviceAccountName" . }}
  labels:
{{ include "storj-multinode.labels" . | nindent 4 }}
{{- end -}}
